# Generated by Django 3.1.5 on 2021-06-22 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lease',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
    ]
