# Generated by Django 3.1.5 on 2021-08-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('accounts', '0002_user_default_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.city'),
        ),
    ]
