# Generated by Django 3.1.5 on 2021-08-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210805_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_city',
        ),
    ]
