# Generated by Django 3.1.5 on 2021-01-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20210128_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
    ]
