# Generated by Django 3.1.5 on 2021-01-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='properties.property'),
        ),
    ]
