# Generated by Django 3.1.5 on 2021-01-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20210128_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='deleted_image_name',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
