# Generated by Django 3.1.5 on 2021-01-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20210130_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='thumbnail_image',
            new_name='thumbnail_photo',
        ),
    ]
