# Generated by Django 3.1.5 on 2021-01-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_property_thumbnail_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='thumbnail_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
