# Generated by Django 3.1.5 on 2021-01-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20210131_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to=''),
        ),
    ]
