# Generated by Django 3.1.5 on 2021-02-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20210131_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='thumbnail_image',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
    ]
