# Generated by Django 3.1.5 on 2021-06-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20210204_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='user',
            new_name='owner',
        ),
    ]
